### ISSUE TITLE
[table-wrap] error

### ISSUE THREAD

**Issue by simoami** [filipstefansson/bootstrap-3-shortcodes#100]
```
Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /home/user/public_html/wp-content/plugins/bootstrap-3-shortcodes/bootstrap-shortcodes.php on line 2005
```

$doc->saveHTML(); this instance method does not take parameters. You probably used the class version.

**Comment by MWDelaney** [comment]
Hi.
I can't seem to reproduce this issue; can you post the shortcode and its contents from your WordPress editor so I can see exactly what you're doing?

**Comment by simoami** [comment]
@MWDelaney 
Quoting the documentation on saveHTML:

```php
public string DOMDocument::saveHTML ([ DOMNode $node = NULL ] )
```
> Changelog:
> 5.3.6	The node parameter was added.

I happen to have a version of php inferior to 5.3.6. so the input parameter was not supported back then.
