### ISSUE TITLE
Can't get carousel to work

### ISSUE THREAD

**Issue by thomasvs** [filipstefansson/bootstrap-3-shortcodes#103]
Hi,

I am trying to get the carousel short code to work, but haven't been successful so far.

There is no specific button to add a carousel (compared to say, adding tabs).  I pasted in the shortcode, but it does not get replaced as I expected.  I then realized that maybe all shortcodes should be prefixed with bp_ - as that is what clicking one of the bootstrap items in the editor wrote as a shortcode.  Still, no go.  I thought it might be javascript-related, so I tried some other things by hand and they all worked, including tabs.  The only one I can't make work is a carousel.

Any idea what could be wrong?

Attaching an image of the post as displayed, and the same post in the editor:

![screenshot from 2015-02-13 00 09 15](https://cloud.githubusercontent.com/assets/248196/6182647/645af686-b316-11e4-90f6-efaa30ed2d8a.png)

![screenshot from 2015-02-13 00 23 12](https://cloud.githubusercontent.com/assets/248196/6182654/8c7e587e-b316-11e4-9d8e-6f835dde6c63.png)

**Comment by MWDelaney** [comment]
It actually doesn't look like you have this plugin installed. This plugin creates a tell-tale purple [B] button next to the "Add Media" button in WordPress, and doesn't create any TinyMCE buttons at all. 

It looks instead like you have [this plugin](https://wordpress.org/plugins/bootstrap-shortcodes/) installed, which unfortunately is not developed by us and for which we cannot provide support.
