### ISSUE TITLE
xclass

### ISSUE THREAD

**Issue by Kapitol** [filipstefansson/bootstrap-3-shortcodes#108]
xclass is not working for me in either scenario, column or image

```
[carousel-item active="true"]
    [column md="5" xclass="archi"]
        [img responsive="true" xclass="monde"]<img src="http://www.current.dev/wp-content/uploads/2015/05/Archimonde.png" alt="Archimonde" width="859" height="751" />[/img]
    [/column]
    [column md="7"]
        [img responsive="true"]<img src="http://www.current.dev/wp-content/uploads/2015/05/warlords-of-draenor-logo.png" alt="warlords of draenor logo" width="486" height="300" />[/img]
        <h3 class="h5">Alliance</h3>
        <h6 class="h3">US - Sargeras</h6>
    [/column]
[/carousel-item]
```
Generated code

```
<div class="item active">
    <div class=" col-md-5">
        <img src="http://www.current.dev/wp-content/uploads/2015/05/Archimonde.png" alt="Archimonde" width="859" height="751" class="  img-responsive">
    </div>
    <div class=" col-md-7">
        <img src="http://www.current.dev/wp-content/uploads/2015/05/warlords-of-draenor-logo.png" alt="warlords of draenor logo" width="486" height="300" class="  img-responsive">
        <h3>Alliance</h3>
        <h6>US – Sargeras</h6>
    </div>
</div>
```
Using version Version 3.3.6 and WordPress 4.2.2

**Comment by Kapitol** [comment]
I tested this on a fresh install on another macintosh. I am running into the same issue. Xclass classes are getting ripped out. Tested on the latest versions of Firefox developer ed. Chrome and Safari. Is anyone watching github?

**Comment by MWDelaney** [comment]
Thank you for the report. I'll look into this issue as soon as possible. 



—

**Comment by MWDelaney** [comment]
Hello,
I reviewed this issue and the stripping of classes is actually intentional to avoid spacing and alignment issues that usually accompany using a carousel for images inserted with the WordPress editor. I've just committed a change that strips ONLY the alignment classes that cause the most issues. Can you test this change and let  us know if it does the trick?

Thanks again for the report.

**Comment by Kapitol** [comment]
MWDelaney, your update fixed the problem. Thank you.
