### ISSUE TITLE
wordpress doesn't work with your last version

### ISSUE THREAD

**Issue by sametp** [filipstefansson/bootstrap-3-shortcodes#113]
I have some problem about wordpress last version. It has mistake at your plugin. I used multisite wordpress. Could you tell me how can I edit that. 

Thanks for now.

Best regards.

**Comment by MWDelaney** [comment]
Can you describe what does or doesn't work with your WordPress installation? We support both the latest public release version of WordPress and WordPress Multisite.

**Comment by sametp** [comment]
ı added at theme's functions.php. That was as this link. http://imgur.com/MQ7K92h

**Comment by MWDelaney** [comment]
Please try installing this plugin as a normal plugin, from the Plugins screen, rather than including it in your theme's functions.php. Let me know if that works.

**Comment by sametp** [comment]
Okay. This is working when I get it on wordpress website. Thanks for your helping but I wanna add this plugin in that theme with function php.
