### ISSUE TITLE
Using collapses outside of collapsibles shortcode

### ISSUE THREAD

**Issue by rogerlos** [filipstefansson/bootstrap-3-shortcodes#121]
I believe bootstrap allows the use of collapses outside of an accordion-style set of collapses. If you do this using Bootstrap 3 Shortcodes, PHP will throw errors. If you changed the function `bs_collapse` to reflect the following changes, `[collapse]` would work fine with or without the surrounding `[collapsibles]` shortcode.

Line 1321 (added test for global):
```php
$parent = isset( $GLOBALS['collapsibles_count'] ) ? 
    'custom-collapse-' . $GLOBALS['collapsibles_count'] : null;
```

Line 1330 (removed `data-parent=""` wrapper from `%4`):
```php
<a class="%3$s" data-toggle="collapse"%4$s href="#%5$s">%6$s</a>
```

Line 1340 (add ternary to see if `$parent` was null, if not, added data wrapper back in):
```php
$parent !== null ? ' data-parent="#' . $parent . '""' : '',
 ```

**Comment by MWDelaney** [comment]
This should be all set! Thank you for this report.

**Comment by rogerlos** [comment]
No worries, thanks for the plugin!
