### ISSUE TITLE
How can i embed it in my theme

### ISSUE THREAD

**Issue by webtrics** [filipstefansson/bootstrap-3-shortcodes#122]
we are creating a theme for themeforest and want to embed it in. how can i do that. reference is given in function.php file its working but button is not showing

**Comment by MWDelaney** [comment]
Rather than embedding the plugin in a theme, I recommend making it a "required plugin" using a tool like [TGM Plugin Activation](http://tgmpluginactivation.com). This way the plugin can remain up to date without you having to update your theme every time we release a new version!
