### ISSUE TITLE
Shortcake cooperation ?

### ISSUE THREAD

**Issue by StaggerLeee** [filipstefansson/bootstrap-3-shortcodes#123]
Shortcake will soon be in the WordPress core. Could you contact them and make your shortcodes work with Shortcake API ?

I can say it would be something very revolutionary.

https://github.com/wp-shortcake/shortcake

**Comment by MWDelaney** [comment]
I would love to see this and I've looked into it before, but from my research Shortcake's previewing tools only work with block-level elements, so columns and other Bootstrap elements that need to appear side-by-side or inline wouldn't preview correctly with Shortcake.

At present we're not planning to implement Shortcake support until inline previews are supported.

**Comment by StaggerLeee** [comment]
Thanks, Despite I dont understand. By "inline" you mean editing values in TinyMce textarea directly ?

Shortcake doesnt limit you how you arrange things in modal box, as I know it.
Dont know, feels as your plugin is more aesy to adapt tnan many other they are adapting to Shortcake.

This man use Shortcake and HTML tables for backend part, clean Bootstrap for frontend part:
https://github.com/gambitph/Page-Builder-Sandwich

Maybe something for inspiration.

Needs to be called themes Bootstrap files in backend too.

**Comment by mwdelaneytwg** [comment]
I mean that, at least the last time I looked, Shortcake didn't let you insert a shortcode with a preview in TinyMCE and have text wrap around the preview, or show it in-line with the text. All previews are "block" elements.

The last time I did any reading on this it was a limitation of how TinyMCE works and that Shortcake couldn't do anything about it.

**Comment by StaggerLeee** [comment]
I know it is not easy to turn and do something completely different.
Try to do what you can and skip rows, columns...

Just my humble advice is, it goes in the code, is major thing for any CMS (Drupal and Joomla will not have it), all developers will jump this wagon, people will prefer a plugin with preview instead of mess with raw shortcodes in text if there are two similar.

What to do. It is not me, or you, deciding course of WordPress. It is just to try to follow the game.
