### ISSUE TITLE
Multiple modals

### ISSUE THREAD

**Issue by jonathanvw** [filipstefansson/bootstrap-3-shortcodes#98]
It seems that multiple modals within a single post aren't working because the href of the toggle anchor and the id of the modal wrapper window are the same for every instance of the modal on the page.

**Comment by MWDelaney** [comment]
@jonathanvw hi, thanks for reporting this.

I can't seem to reproduce the issue in the latest version of this plugin. The href and toggle anchor are based each modal's title --are you using the same title, or no maybe title for both modals?

**Comment by jonathanvw** [comment]
Ah, that explains it.  I was indeed using the same title for the multiple
modals. Maybe a small note in the read me is all it needs to help folks
like me.  :) cheers and thanks for the plugin.

**Comment by MWDelaney** [comment]
Do they need to have the same title? If this is something you need, if it's a legitimate use-case, we can look into making it work.

**Comment by jonathanvw** [comment]
In this case i can use different titles, but i think there may be
legitimate times where someone wants multiple modals with no title at all.

**Comment by scharc** [comment]
I have the same problem... I have a couple of projects with the same layout on the same page and want to trigger for each of them a modal with the project content... each trigger-link should have the same name on the button..

maybe you could provide an id-element for this purpose?

**Comment by MWDelaney** [comment]
This is actually resolved by 752e0593c5f1608b474329b1918f84a0876d7e47 !
